"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useLang } from "@/lib/lang";

/**
 * ATHA Ops Console — live control surface for the REAL agent system.
 *
 * When the site runs on a Node server (dev / standalone) every button spawns
 * the real Python agents (atha-os-live/) and prints their REAL results.
 * When the page is served from the static GitHub Pages export the API is
 * absent by design, and the console falls back to the last baked real
 * report (/atha/report.json) — clearly labelled as offline evidence.
 */

type Severity = "critical" | "high" | "medium" | "low" | "info";

type Finding = {
  severity?: Severity | string;
  type?: string;
  target?: string;
  component?: string;
  description?: string;
  line?: number;
  real_action?: boolean;
  simulated?: boolean;
};

type ApiResult = {
  success?: boolean;
  error?: string;
  agents_registered?: number;
  real_mode?: boolean;
  stats?: Record<string, unknown> | null;
  target?: string;
  generated_by?: string;
  scans?: Record<string, Record<string, unknown>>;
  drift?: Record<string, unknown>;
  sensitive_inventory?: { risky_world_readable?: string[] };
  backups?: string[];
  findings?: Finding[];
  total?: number;
  files_scanned?: number;
  open_ports?: number[];
  status?: string;
  steps_executed?: number;
  total_steps?: number;
  teams_involved?: string[];
  steps_by_team?: Record<string, { step?: string; agent?: string; success?: boolean }[]>;
  total_findings?: number;
  failures?: { agent?: string; step?: string; error?: string }[];
  results?: { agent?: string; step?: string; success?: boolean }[];
  assessment?: string;
  workflow_id?: string;
  reason?: string;
};

const SEV_COLOR: Record<string, string> = {
  critical: "text-red-400 border-red-400/40 bg-red-400/10",
  high: "text-red-300 border-red-300/40 bg-red-300/10",
  medium: "text-amber-300 border-amber-300/40 bg-amber-300/10",
  low: "text-sky-300 border-sky-300/40 bg-sky-300/10",
  info: "text-neutral-400 border-neutral-400/30 bg-neutral-400/10",
};

const COPY = {
  en: {
    kicker: "LIVE OPERATIONS",
    title: "Agent Ops Console",
    sub: "Real agents. Real target. No sandbox.",
    status: "System status",
    agents: "agents registered",
    realMode: "REAL MODE",
    target: "Protected target",
    actions: "Run a real operation",
    fullReport: "Full report",
    network: "Network scan",
    secrets: "Secrets scan",
    vulns: "Vulnerability scan",
    malware: "Malware scan",
    assess: "Maestro assess & respond",
    drift: "Integrity drift check",
    liveCheck: "Live deployment integrity",
    baseline: "Establish baseline",
    defense: "Defense status",
    workflow: "Run workflow",
    running: "AGENTS WORKING…",
    offlineTitle: "Offline evidence",
    offlineSub:
      "This static deployment has no agent runtime. Below is the last report generated by the real system — evidence and timestamps included.",
    findings: "findings",
    filesScanned: "files scanned",
    openPorts: "open ports",
    noFindings: "Clean — no findings.",
    real: "REAL",
    sim: "SIM",
    raw: "Raw JSON",
    steps: "steps",
    failures: "failures",
    clean: "clean",
    lastRun: "Report generated",
    mode: "Source",
    live: "Live run",
    baked: "Baked report",
    backHome: "← Back to site",
  },
  "pt-br": {
    kicker: "OPERAÇÕES AO VIVO",
    title: "Console de Operações",
    sub: "Agentes reais. Alvo real. Sem sandbox.",
    status: "Estado do sistema",
    agents: "agentes registrados",
    realMode: "MODO REAL",
    target: "Alvo protegido",
    actions: "Rodar operação real",
    fullReport: "Relatório completo",
    network: "Scan de rede",
    secrets: "Scan de segredos",
    vulns: "Scan de vulnerabilidades",
    malware: "Scan de malware",
    assess: "Maestro: avaliar e responder",
    drift: "Checar drift de integridade",
    liveCheck: "Integridade do deploy ao vivo",
    baseline: "Estabelecer baseline",
    defense: "Status da defesa",
    workflow: "Rodar workflow",
    running: "AGENTES TRABALHANDO…",
    offlineTitle: "Evidência offline",
    offlineSub:
      "Este deploy estático não tem runtime de agentes. Abaixo, o último relatório gerado pelo sistema real — com evidências e timestamps.",
    findings: "achados",
    filesScanned: "arquivos varridos",
    openPorts: "portas abertas",
    noFindings: "Limpo — nenhum achado.",
    real: "REAL",
    sim: "SIM",
    raw: "JSON bruto",
    steps: "passos",
    failures: "falhas",
    clean: "limpo",
    lastRun: "Relatório gerado",
    mode: "Fonte",
    live: "Execução ao vivo",
    baked: "Relatório embutido",
    backHome: "← Voltar ao site",
  },
} as const;

const WORKFLOWS = [
  "self_test",
  "vulnerability_remediation",
  "incident_response",
  "failure_recovery",
  "data_corruption_recovery",
];

function basePath() {
  return process.env.NEXT_PUBLIC_BASE_PATH || "";
}

export default function OpsConsole() {
  const [lang] = useLang();
  const t = COPY[lang];
  const [result, setResult] = useState<ApiResult | null>(null);
  const [label, setLabel] = useState<string>("");
  const [busy, setBusy] = useState(false);
  const [live, setLive] = useState<boolean | null>(null);
  const [showRaw, setShowRaw] = useState(false);
  const bootRef = useRef(false);

  const apply = useCallback((data: ApiResult, sourceLabel: string) => {
    setResult(data);
    setLabel(sourceLabel);
    setShowRaw(false);
  }, []);

  const runAction = useCallback(
    async (action: string, workflow?: string) => {
      setBusy(true);
      setShowRaw(false);
      try {
        const res = await fetch(`${basePath()}/api/atha`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ action, workflow }),
        });
        const data = (await res.json()) as ApiResult;
        setLive(true);
        apply(data, `${t.live} · ${new Date().toLocaleTimeString()}`);
      } catch {
        // No server runtime (static deploy) → load baked real report.
        try {
          const res = await fetch(`${basePath()}/atha/report.json`, { cache: "no-store" });
          const data = (await res.json()) as ApiResult;
          setLive(false);
          apply(data, t.baked);
        } catch {
          setLive(false);
          apply({ success: false, error: "offline_no_report" }, t.baked);
        }
      } finally {
        setBusy(false);
      }
    },
    [apply, t]
  );

  useEffect(() => {
    if (bootRef.current) return;
    bootRef.current = true;
    runAction("status");
  }, [runAction]);

  const scanFindings = (scans: ApiResult["scans"]) => {
    if (!scans) return [] as { scan: string; f: Finding }[];
    const out: { scan: string; f: Finding }[] = [];
    for (const [scan, data] of Object.entries(scans)) {
      for (const f of (data?.findings as Finding[]) ?? []) out.push({ scan, f });
    }
    return out;
  };

  const findings = result?.scans ? scanFindings(result.scans) : (result?.findings ?? []).map((f) => ({ scan: "", f }));

  const buttons: { key: string; action: string; wf?: boolean }[] = [
    { key: t.fullReport, action: "full_report" },
    { key: t.network, action: "network_scan" },
    { key: t.secrets, action: "secrets_scan" },
    { key: t.malware, action: "malware_scan" },
    { key: t.defense, action: "defense_status" },
    { key: t.vulns, action: "vuln_scan" },
    { key: t.assess, action: "assess" },
    { key: t.drift, action: "drift" },
    { key: t.liveCheck, action: "live_check" },
    { key: t.baseline, action: "baseline" },
  ];

  return (
    <div className="mx-auto w-full max-w-5xl px-5 pb-24 pt-24 font-sans text-neutral-200">
      {/* Header */}
      <a href={`${basePath()}/`} className="mb-10 inline-block text-sm text-neutral-500 transition-colors hover:text-amber-300">
        {t.backHome}
      </a>
      <p className="font-mono text-[11px] tracking-[0.3em] text-amber-400">{t.kicker}</p>
      <h1 className="mt-2 text-4xl font-semibold tracking-tight text-white md:text-5xl">{t.title}</h1>
      <p className="mt-3 max-w-xl text-sm leading-relaxed text-neutral-400">{t.sub}</p>

      {/* Status bar */}
      <div className="mt-8 grid gap-3 rounded-2xl border border-neutral-800 bg-neutral-950/60 p-5 sm:grid-cols-3">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-500">{t.status}</p>
          <p className="mt-1 flex items-center gap-2 text-sm text-white">
            <span
              className={`inline-block h-2 w-2 rounded-full ${
                result?.real_mode || live === true
                  ? "bg-emerald-400"
                  : live === false
                    ? "bg-amber-400"
                    : "bg-neutral-600"
              }`}
            />
            {result?.real_mode
              ? t.realMode
              : live === true
                ? "online"
                : busy
                  ? t.running
                  : t.offlineTitle}
          </p>
          {result?.agents_registered != null && (
            <p className="mt-0.5 text-xs text-neutral-500">
              {result.agents_registered} {t.agents}
            </p>
          )}
        </div>
        <div>
          <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-500">{t.target}</p>
          <p className="mt-1 truncate font-mono text-xs text-neutral-300">
            {result?.target ?? (result?.stats?.target_root as string) ?? "—"}
          </p>
        </div>
        <div>
          <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-500">{t.mode}</p>
          <p className="mt-1 text-xs text-neutral-300">{label || "—"}</p>
        </div>
      </div>

      {/* Actions */}
      <div className="mt-8">
        <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-500">{t.actions}</p>
        <div className="mt-3 flex flex-wrap gap-2">
          {buttons.map((b) => (
            <button
              key={b.action}
              disabled={busy}
              onClick={() => runAction(b.action)}
              className="rounded-full border border-neutral-700 bg-neutral-900/70 px-4 py-2 text-xs font-medium text-neutral-200 transition-all hover:border-amber-400/60 hover:text-amber-300 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {b.key}
            </button>
          ))}
          <div className="flex items-center gap-2">
            <select
              id="atha-wf"
              defaultValue={WORKFLOWS[0]}
              disabled={busy}
              className="rounded-full border border-neutral-700 bg-neutral-900/70 px-3 py-2 text-xs text-neutral-300 outline-none focus:border-amber-400/60"
            >
              {WORKFLOWS.map((w) => (
                <option key={w} value={w}>
                  {w}
                </option>
              ))}
            </select>
            <button
              disabled={busy}
              onClick={() => {
                const el = document.getElementById("atha-wf") as HTMLSelectElement | null;
                runAction("workflow", el?.value ?? WORKFLOWS[0]);
              }}
              className="rounded-full bg-amber-400 px-4 py-2 text-xs font-semibold text-black transition-all hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {t.workflow}
            </button>
          </div>
        </div>
      </div>

      {/* Busy indicator */}
      {busy && (
        <div className="mt-6 flex items-center gap-3 rounded-xl border border-amber-400/30 bg-amber-400/5 px-4 py-3">
          <span className="h-2.5 w-2.5 animate-ping rounded-full bg-amber-400" />
          <span className="font-mono text-xs tracking-widest text-amber-300">{t.running}</span>
        </div>
      )}

      {/* Offline notice */}
      {live === false && result && (
        <div className="mt-6 rounded-xl border border-neutral-800 bg-neutral-900/40 px-4 py-3 text-xs leading-relaxed text-neutral-400">
          <span className="font-semibold text-neutral-200">{t.offlineTitle}: </span>
          {t.offlineSub}
        </div>
      )}

      {/* Output */}
      {result && !busy && (
        <div className="mt-6 space-y-4">
          {result.error && (
            <div className="rounded-xl border border-red-400/40 bg-red-400/10 px-4 py-3 font-mono text-xs text-red-300">
              error: {result.error}
            </div>
          )}

          {/* Workflow result */}
          {result.workflow_id && (
            <div className="rounded-2xl border border-neutral-800 bg-neutral-950/60 p-5">
              <div className="flex flex-wrap items-center gap-3">
                <span className="font-mono text-sm text-white">{result.workflow_id}</span>
                <span
                  className={`rounded-full border px-2.5 py-0.5 font-mono text-[10px] tracking-widest ${
                    result.status === "completed"
                      ? "border-emerald-400/40 bg-emerald-400/10 text-emerald-300"
                      : "border-red-400/40 bg-red-400/10 text-red-300"
                  }`}
                >
                  {result.status}
                </span>
                <span className="font-mono text-xs text-neutral-500">
                  {result.steps_executed ?? result.total_steps ?? "—"} {t.steps} ·{" "}
                  {result.failures?.length ?? 0} {t.failures}
                </span>
              </div>
              {result.teams_involved && result.teams_involved.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1.5">
                  {result.teams_involved.map((team) => (
                    <span
                      key={team}
                      className="rounded-full border border-neutral-700 bg-neutral-900/70 px-2.5 py-0.5 font-mono text-[10px] tracking-widest text-neutral-400"
                    >
                      {team}
                    </span>
                  ))}
                </div>
              )}
              {result.results && (
                <div className="mt-3 grid gap-1.5 sm:grid-cols-2">
                  {result.results.map((r, i) => (
                    <div key={i} className="flex items-center gap-2 font-mono text-[11px]">
                      <span className={r.success ? "text-emerald-400" : "text-red-400"}>
                        {r.success ? "✓" : "✗"}
                      </span>
                      <span className="text-neutral-400">{r.agent}</span>
                      <span className="truncate text-neutral-600">{r.step}</span>
                    </div>
                  ))}
                </div>
              )}
              {!result.results &&
                result.steps_by_team &&
                Object.entries(result.steps_by_team).map(([team, steps]) => (
                  <div key={team} className="mt-3">
                    <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-500">{team}</p>
                    <div className="mt-1.5 grid gap-1.5 sm:grid-cols-2">
                      {steps.map((r, i) => (
                        <div key={i} className="flex items-center gap-2 font-mono text-[11px]">
                          <span className={r.success ? "text-emerald-400" : "text-red-400"}>
                            {r.success ? "✓" : "✗"}
                          </span>
                          <span className="text-neutral-400">{r.agent}</span>
                          <span className="truncate text-neutral-600">{r.step}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
            </div>
          )}

          {/* Summary chips */}
          {result.scans && (
            <div className="flex flex-wrap gap-2">
              <Chip label={t.filesScanned} value={String(result.scans.secrets?.files_scanned ?? "—")} />
              <Chip label={t.findings} value={String(findings.length)} />
              <Chip
                label={t.openPorts}
                value={(result.scans.network?.open_ports as number[])?.join(", ") ?? "—"}
              />
              <Chip
                label="drift"
                value={result.drift?.drift_detected ? "detected" : result.drift ? t.clean : "—"}
              />
            </div>
          )}

          {/* Findings */}
          {findings.length > 0 ? (
            <div className="space-y-2">
              {findings.map(({ scan, f }, i) => (
                <div
                  key={i}
                  className={`rounded-xl border px-4 py-3 ${SEV_COLOR[String(f.severity).toLowerCase()] ?? SEV_COLOR.info}`}
                >
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-mono text-[10px] uppercase tracking-widest opacity-80">
                      {f.severity}
                    </span>
                    <span className="font-mono text-xs">{f.type ?? scan}</span>
                    {f.target && <span className="truncate font-mono text-[11px] opacity-70">{f.target}</span>}
                    <span className="ml-auto rounded border border-current/30 px-1.5 py-0.5 font-mono text-[9px] tracking-widest">
                      {f.simulated ? t.sim : t.real}
                    </span>
                  </div>
                  {f.description && <p className="mt-1 text-xs leading-relaxed opacity-90">{f.description}</p>}
                </div>
              ))}
            </div>
          ) : (
            result.scans && (
              <p className="rounded-xl border border-emerald-400/30 bg-emerald-400/5 px-4 py-3 font-mono text-xs text-emerald-300">
                {t.noFindings}
              </p>
            )
          )}

          {/* Maestro assessment */}
          {result.assessment && (
            <div className="rounded-xl border border-amber-400/30 bg-amber-400/5 px-4 py-3 font-mono text-xs text-amber-200">
              maestro: {result.assessment}
              {result.reason ? ` — ${result.reason}` : ""}
            </div>
          )}

          {/* Raw JSON */}
          <button
            onClick={() => setShowRaw((v) => !v)}
            className="font-mono text-[11px] tracking-widest text-neutral-500 transition-colors hover:text-amber-300"
          >
            {showRaw ? "▾" : "▸"} {t.raw}
          </button>
          {showRaw && (
            <pre className="max-h-96 overflow-auto rounded-xl border border-neutral-800 bg-black p-4 font-mono text-[11px] leading-relaxed text-neutral-400">
              {JSON.stringify(result, null, 2)}
            </pre>
          )}
        </div>
      )}
    </div>
  );
}

function Chip({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-full border border-neutral-800 bg-neutral-950/60 px-4 py-1.5 font-mono text-[11px]">
      <span className="text-neutral-500">{label}: </span>
      <span className="text-neutral-200">{value}</span>
    </div>
  );
}
